const PHOTOS = [

  {
    id:       0,
    src:      'photos/fghdfghgf.jpg',
    thumb:    'photos/fghdfghgf.jpg',
    title:    'Tunnel de lumière',
    location: 'Paris, FR',
    year:     '2024',
    camera:   'Nikon FM2',
    film:     'Kodak Ektar 100',
    desc:     'Une exploration des espaces souterrains parisiens, où la lumière artificielle crée un ballet incessant de reflets et d\'ombres.',
  },

  {
    id:       1,
    src:      'photos/fghjgfh.jpg',
    thumb:    'photos/fghjgfh.jpg',
    title:    'Silence venteux',
    location: 'Brest, FR',
    year:     '2024',
    camera:   'Canon AE-1',
    film:     'Ilford HP5',
    desc:     'Portrait capturé dans la lumière rasante de l\'après-midi. Le vent, invisible, devient presque matière.',
  },

  {
    id:       2,
    src:      'photos/gfdgsdfrgs.jpg',
    thumb:    'photos/gfdgsdfrgs.jpg',
    title:    'Contre-jour',
    location: 'Marseille, FR',
    year:     '2023',
    camera:   'Pentax K1000',
    film:     'Fuji Velvia 50',
    desc:     'La silhouette se fond dans la lumière orangée du soir. Un instant suspendu entre deux mondes.',
  },

  {
    id:       3,
    src:      'photos/sergdfg.jpg',
    thumb:    'photos/sergdfg.jpg',
    title:    'Altitude zéro',
    location: 'Alpes, FR',
    year:     '2023',
    camera:   'Nikon FM2',
    film:     'Kodak Portra 400',
    desc:     'Les sommets s\'effacent dans la brume matinale. Une géographie de l\'impermanence.',
  },

  {
    id:       4,
    src:      'photos/srdtgserthb.jpg',
    thumb:    'photos/srdtgserthb.jpg',
    title:    'Voie lactée',
    location: 'Corse, FR',
    year:     '2023',
    camera:   'Nikon FM2',
    film:     'Kodak T-Max 3200',
    desc:     'Une nuit sans lune, quelque part dans le maquis. La voûte céleste comme seule source de lumière.',
  },

  {
    id:       5,
    src:      'photos/srtghstr.jpg',
    thumb:    'photos/srtghstr.jpg',
    title:    'Brume de Seine',
    location: 'Paris, FR',
    year:     '2022',
    camera:   'Canon AE-1',
    film:     'Ilford Delta 400',
    desc:     'L\'aube sur la Seine. La ville encore endormie, recouverte d\'un voile de brume blanche.',
  },

  {
    id:       6,
    src:      'photos/img1.jpg',
    thumb:    'photos/img1.jpg',
    title:    'Perspective',
    location: 'Lyon, FR',
    year:     '2022',
    camera:   'Olympus OM-1',
    film:     'Kodak Ektar 100',
    desc:     'Une rue qui semble converger vers l\'infini. La ville comme exercice de géométrie.',
  },

  {
    id:       7,
    src:      'photos/img2.jpg',
    thumb:    'photos/img2.jpg',
    title:    'Été nordique',
    location: 'Bretagne, FR',
    year:     '2022',
    camera:   'Nikon FM2',
    film:     'Fuji Pro 400H',
    desc:     'La lumière de fin d\'été sur les landes bretonnes. Une palette de verts et d\'or.',
  },

  {
    id:       8,
    src:      'photos/img3.jpg',
    thumb:    'photos/img3.jpg',
    title:    'Marché aux fleurs',
    location: 'Bordeaux, FR',
    year:     '2024',
    camera:   'Leica M6',
    film:     'Kodak Portra 160',
    desc:     'Le chaos coloré du marché du dimanche. Des bouquets qui disparaissent aussitôt achetés.',
  },

  {
    id:       10,
    src:      'photos/img4.jpg',
    thumb:    'photos/img4.jpg',
    title:    'Cité ensoleillée',
    location: 'Bordeaux, FR',
    year:     '2024',
    camera:   'Leica M6',
    film:     'Kodak Portra 160',
    desc:     'Le chaos coloré du marché du dimanche. Des bouquets qui disparaissent aussitôt achetés.',
  },

  {
    id:       11,
    src:      'photos/img5.jpg',
    thumb:    'photos/img5.jpg',
    title:    'Cité ensoleillée',
    location: 'Bordeaux, FR',
    year:     '2024',
    camera:   'Leica M6',
    film:     'Kodak Portra 160',
    desc:     'Le chaos coloré du marché du dimanche. Des bouquets qui disparaissent aussitôt achetés.',
  },

  {
    id:       12,
    src:      'photos/img6.jpg',
    thumb:    'photos/img6.jpg',
    title:    'Cité ensoleillée',
    location: 'Bordeaux, FR',
    year:     '2024',
    camera:   'Leica M6',
    film:     'Kodak Portra 160',
    desc:     'Le chaos coloré du marché du dimanche. Des bouquets qui disparaissent aussitôt achetés.',
  },

  {
    id:       13,
    src:      'photos/img7.jpg',
    thumb:    'photos/img7.jpg',
    title:    'Cité ensoleillée',
    location: 'Bordeaux, FR',
    year:     '2024',
    camera:   'Leica M6',
    film:     'Kodak Portra 160',
    desc:     'Le chaos coloré du marché du dimanche. Des bouquets qui disparaissent aussitôt achetés.',
  },

  {
    id:       14,
    src:      'photos/img8.jpg',
    thumb:    'photos/img8.jpg',
    title:    'Cité ensoleillée',
    location: 'Bordeaux, FR',
    year:     '2024',
    camera:   'Leica M6',
    film:     'Kodak Portra 160',
    desc:     'Le chaos coloré du marché du dimanche. Des bouquets qui disparaissent aussitôt achetés.',
  },

];